export const data = {
    date:new Date(),
    city: [
        {
            name:'Almaty',
            x:12,
            y:30,
        },
        {
            name:'Astana',
            x:20,
            y:49,
        },
        {
            name:'Moscow',
            x:50,
            y:-159,
        },
        {
            name:'London',
            x:-490,
            y:200,
        },
        {
            name:'Dubai',
            x:500,
            y:-49,
        }
    ],
    transport:[
        {name:'plane',
            speed:4,
            cost:40
        },
        {name:'car',
            speed:2,
            cost:20
        },
        {name:'train',
            speed:3,
            cost:30
        },
        {
            name:'bus',
            speed:0.5,
            cost: 10
        }
    ]
}
